baseURL = "https://cyber-hub-1705.pages.dev/"
relativeURLs = false
canonifyURLs = true
languageCode = "en-us"
title = "My Project"
timeout = "45s"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[module]
  [[module.imports]]
    path = "github.com/jpanther/congo/v2"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  