[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 1
  [en.params]
    title = "Marketing Hub (EN)"

[uk]
  languageName = "Українська"
  contentDir = "content/uk"
  weight = 2
  [uk.params]
    title = "Маркетинговий Хаб (UA)"

[de]
  languageName = "Deutsch"
  contentDir = "content/de"
  weight = 3

[fr]
  languageName = "Français"
  contentDir = "content/fr"
  weight = 4

[es]
  languageName = "Español"
  contentDir = "content/es"
  weight = 5

[ru]
  languageName = "Русский"
  contentDir = "content/ru"
  weight = 6

[zh]
  languageName = "中文"
  contentDir = "content/zh"
  weight = 7

[tr]
  languageName = "Türkçe"
  contentDir = "content/tr"
  weight = 8

[ga]
  languageName = "Gaeilge"
  contentDir = "content/ga"
  weight = 9
