# ==========================================
# ГОЛОВНЕ МЕНЮ НАВІГАЦІЇ (УКРАЇНСЬКА)
# ==========================================

[[main]]
  name = "Головна"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Блоги/Пости"
  pageRef = "/posts"
  weight = 20

[[main]]
  name = "Наші роботи"
  pageRef = "/works"
  weight = 30

[[main]]
  name = "Контакти"
  pageRef = "/contact"
  weight = 40